### PR TITLE
HSEARCH-1849 Using UninvertingReader for sorting on non doc value fields

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Sanne, just in case, only the last commit of this is what this PR is about.

**Comment by gunnarmorling** [comment]
Rebased and added some more commits.

**Comment by gunnarmorling** [comment]
Tada, _orm_ compiling now :)

**Comment by Sanne** [comment]
merged and pushed to my Lucene5 branch

**Pull request merged**
